### ISSUE TITLE
这个组件用compose安装有问题呢？

### ISSUE THREAD

**Issue by maolin51** [fatrellis/mqk#1]
这个组件用compose安装有问题呢？
提示以下这个：
 php artisan optimize
Generating optimized class loader
The compiled services file has been removed.

**Comment by fatrellis** [comment]
先不要引入到其他项目，我还没有测试过。你先git clone下来，然后composer install。这个过程你可以尝试写在README.md里面PR给我。

**Comment by fatrellis** [comment]
@maolin51 如果可以你也可以排查问题，把这个bug解决。

**Comment by maolin51** [comment]
好的，我在看了，现在直接git clone 这个安装没问题的。 在已经有的项目里安装该组件，我看部分代码已经编译成功，我尝试下看是否能用， 有问题再联系你哟

**Comment by fatrellis** [comment]
你先看看，是否可以完成测试。里面有一个脚本是监控每秒消费数量的。在test里面。

**Comment by fatrellis** [comment]
新版本已经解决。
